services:
  - type: worker
    name: warn-bot
    env: python
    buildCommand: ""
    startCommand: "python main.py"
    envVars:
      - key: TOKEN
        sync: false
      - key: TARGET_ID
        sync: false
